version: "2.0"
services:
  main:
    image: quay.io/jupyter/pytorch-notebook:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      - JUPYTER_TOKEN=${ADMIN_PASSWORD}
    volumes:
      - ./storage:/home/jovyan
    ports:
      - 172.17.0.1:3895:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
