version: "2.0"
services:
  main:
    image: tverous/pytorch-notebook:${SOFTWARE_VERSION_TAG}
    environment:
      - JUPYTER_TOKEN=${ADMIN_PASSWORD}
    volumes:
      - ./local_vol:/docker_vol
    ports:
      - 172.17.0.1:3895:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
